export enum PurchasesEnum {
  WeakQualities = 'com.gravitino.weak-qualities',
  Professions = 'com.gravitino.professions',
  StrongQualities = 'com.gravitino.strong-qualities',
  Ancestors = 'com.gravitino.ancestors',
  TotemicAnimals = 'com.gravitino.totemic-animals',
  DestinyProgram = 'com.gravitino.destiny-program',
  LuckyNumbers = 'com.gravitino.lucky-numbers',
  Karma = 'com.gravitino.karma',
  GuessingNumber = 'com.gravitino.guessing-number',
  Compatibility = 'com.gravitino.compatibility',
  PhoneCalculation = 'com.gravitino.phone-calculation',
  HouseCalculation = 'com.gravitino.house-calculation',
  FateNumberGifts = 'com.gravitino.fate-number-gifts',
  Aromatherapy = 'com.gravitino.aromatherapy',
  RunicFormulas = 'com.gravitino.runic-formulas',
  Graphs = 'com.gravitino.graphs',
  Diseases = 'com.gravitino.diseases',
}
