export const AppStrings = {
  AUTH_CODE_PHONE_SEND_OPERATION: 'Отправка кода по номеру телефона',
  AUTH_CODE_EMAIL_SEND_OPERATION: 'Отправка кода по E-Mail',
  AUTH_CODE_SEND_RESPONSE: 'Код успешно отправлен',

  CATEGORY_GET_ALL_OPERATION: 'Получение списка всех категорий',
  CATEGORY_GET_ALL_RESPONSE: 'Категории успешно получены',
  CATEGORY_UPDATE_OPERATION: 'Изменение категории',
  CATEGORY_UPDATE_RESPONSE: 'Категория успешно изменена',

  LANGUAGE_CREATE_OPERATION: 'Создание нового языка',
  LANGUAGE_CREATE_RESPONSE: 'Язык успешно создан',
  LANGUAGE_GET_ALL_OPERATION: 'Получение списка всех языков',
  LANGUAGE_GET_ALL_RESPONSE: 'Языки успешно получены',
  LANGUAGE_UPDATE_OPERATION: 'Изменение языка',
  LANGUAGE_UPDATE_RESPONSE: 'Язык успешно изменен',
  LANGUAGE_DELETE_OPERATION: 'Удаление языка',
  LANGUAGE_DELETE_RESPONSE: 'Язык успешно удален',

  ONBOARD_CREATE_OPERATION: 'Создание нового приветственного экрана',
  ONBOARD_CREATE_RESPONSE: 'Приветственный экран успешно создан',
  ONBOARD_GET_ALL_OPERATION: 'Получение списка всех приветственных экранов',
  ONBOARD_GET_ALL_RESPONSE: 'Приветственные экраны успешно получены',
  ONBOARD_UPDATE_OPERATION: 'Изменение приветственного экрана',
  ONBOARD_UPDATE_RESPONSE: 'Приветственный экран успешно изменен',
  ONBOARD_DELETE_OPERATION: 'Удаление приветственного экрана',
  ONBOARD_DELETE_RESPONSE: 'Приветственный экран успешно удален',

  PAGE_CREATE_OPERATION: 'Создание новой страницы',
  PAGE_CREATE_RESPONSE: 'Страница успешно создана',
  PAGE_GET_ALL_OPERATION: 'Получение списка всех страниц',
  PAGE_GET_ALL_RESPONSE: 'Страницы успешно получены',
  PAGE_UPDATE_OPERATION: 'Изменение страницы',
  PAGE_UPDATE_RESPONSE: 'Страница успешно изменен',
  PAGE_DELETE_OPERATION: 'Удаление страницы',
  PAGE_DELETE_RESPONSE: 'Страница успешно удален',

  FATE_CARD_GET_OPERATION: 'Получение карты судьбы пользователя',
  FATE_CARD_GET_RESPONSE: 'Карта судьбы успешно получена',
  FATE_NUMBER_GET_OPERATION: 'Получение числа судьбы пользователя',
  FATE_NUMBER_GET_RESPONSE: 'Число судьбы успешно получено',
  CHRONIC_DISEASE_GET_OPERATION: 'Получение хронического заболевания пользователя',
  CHRONIC_DISEASE_GET_RESPONSE: 'Хроническое заболевание успешно получено',
  HEALTH_NUMEROLOGY_GET_OPERATION: 'Получение нумерологии здоровья',
  HEALTH_NUMEROLOGY_GET_RESPONSE: 'Числа успешно получены',
  PROFESSIONS_GET_OPERATION: 'Получение профессий пользователя',
  PROFESSIONS_GET_RESPONSE: 'Профессии успешно получены',
  WEAK_QUALITIES_GET_OPERATION: 'Получение слабых качеств пользователя',
  WEAK_QUALITIES_GET_RESPONSE: 'Слабые качества успешно получены',
  STRONG_QUALITIES_GET_OPERATION: 'Получение сильных качеств и талантов пользователя',
  STRONG_QUALITIES_GET_RESPONSE: 'Сильные качества и таланты успешно получены',
  PLANETS_GET_OPERATION: 'Получение планет пользователя',
  PLANETS_GET_RESPONSE: 'Планеты успешно получены',
  ANCESTORS_GET_OPERATION: 'Получение предков пользователя',
  ANCESTORS_GET_RESPONSE: 'Предки успешно получены',
  TOTEMIC_ANIMALS_GET_OPERATION: 'Получение тотемных животных пользователя',
  TOTEMIC_ANIMALS_GET_RESPONSE: 'Тотемные животные успешно получены',
  DESTINY_PROGRAM_GET_OPERATION: 'Получение программы судьбы пользователя',
  DESTINY_PROGRAM_GET_RESPONSE: 'Программа судьбы успешно получены',
  LUCKY_NUMBERS_GET_OPERATION: 'Получение чисел удачи пользователя',
  LUCKY_NUMBERS_GET_RESPONSE: 'Числа удачи успешно получены',
  KARMA_GET_OPERATION: 'Получение кармы пользователя',
  KARMA_GET_RESPONSE: 'Карма успешно получены',

  PAGE_TYPE_GET_ALL_OPERATION: 'Получение списка всех типов страниц',
  PAGE_TYPE_GET_ALL_RESPONSE: 'Типы страниц успешно получены',
  PAGE_TYPE_GET_ONE_OPERATION: 'Получение типа страницы',
  PAGE_TYPE_GET_ONE_RESPONSE: 'Тип страницы успешно получены',
  PAGE_TYPE_UPDATE_OPERATION: 'Изменение типа страницы',
  PAGE_TYPE_UPDATE_RESPONSE: 'Тип страницы успешно изменен',

  USERS_CREATE_OPERATION: 'Регистрация пользователя',
  USERS_CREATE_RESPONSE: 'Пользователь успешно зарегистрирован',
  USERS_CHECK_EXISTS_OPERATION: 'Проверка существования пользователя',
  USERS_CHECK_EXISTS_RESPONSE: 'Пользователь (не)зарегистрирован',
  USERS_GET_CURRENT_OPERATION: 'Получение данных текущего пользователя',
  USERS_GET_CURRENT_RESPONSE: 'Данные успешно получены',
  USERS_UPDATE_CURRENT_OPERATION: 'Изменение данных текущего пользователя',
  USERS_UPDATE_CURRENT_RESPONSE: 'Данные успешно изменены',
  USERS_UPDATE_PASSWORD_OPERATION: 'Изменение пароля текущего пользователя',
  USERS_UPDATE_PASSWORD_RESPONSE: 'Пароль успешно изменен',
  USERS_RESET_PASSWORD_OPERATION: 'Сброс пароля текущего пользователя',
  USERS_RESET_PASSWORD_RESPONSE: 'Пароль успешно изменен',
  USERS_DELETE_CURRENT_OPERATION: 'Удаление текущего пользователя',
  USERS_DELETE_CURRENT_RESPONSE: 'Пользователь успешно удален',
}
