import { PageTypesEnum } from 'src/common/constants/constants'
import { Page } from 'src/modules/page/entities/page.entity'
import { MigrationInterface, QueryRunner } from 'typeorm'

export class SeedAromatherapy1715772019952 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.manager.insert(Page, [
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['1'],
        page_name: 'Лидерство, инициатива',
        page_image: '',
        page_content: `- *Масло розмарина* – стимулирует ум и концентрацию, добавляет энергии.
        - *Масло эвкалипта* – освежает, придаёт силы и помогает сосредоточиться.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['2'],
        page_name: 'Гармония, партнёрство',
        page_image: '',
        page_content: `- *Масло ромашки* – успокаивает, уменьшает стресс и способствует миру.
        - *Масло иланг-иланга* – уравновешивает эмоции, способствует релаксации.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['3'],
        page_name: 'Коммуникация, творчество',
        page_image: '',
        page_content: `- *Масло лимона* – стимулирует ум и поднимает настроение.
        - *Масло грейпфрута* – активизирует и освежает, поднимает дух.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['4'],
        page_name: 'Стабильность, порядок',
        page_image: '',
        page_content: `- *Масло кедра* – создаёт ощущение устойчивости и комфорта.
        - *Масло ветивера* – помогает укрепить нервную систему, добавляет уверенности.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['5'],
        page_name: 'Приключение, изменения',
        page_image: '',
        page_content: `- *Масло перечной мяты* – освежает, стимулирует новые идеи, придаёт энергию.
        - *Масло имбиря* – добавляет тепла и остроты, стимулирует движение вперёд.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['6'],
        page_name: 'Забота, ответственность',
        page_image: '',
        page_content: `- *Масло лаванды* – уменьшает анксиозность, способствует спокойствию и заботе.
        - *Масло розы* – улучшает настроение, помогает в эмоциональном балансе.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['7'],
        page_name: 'Духовность, мудрость',
        page_image: '',
        page_content: `- *Масло франкинсенса* – способствует медитации, углублению мыслей.
        - *Масло мирры* – поддерживает духовные практики, углубляет медитативные состояния.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['8'],
        page_name: 'Сила, успех',
        page_image: '',
        page_content: `- *Масло сандала* – помогает углубиться в себя, поддерживает при духовных поисках и медитации.
        - *Масло пачули* – укрепляет энергетический фон, способствует привлечению успеха.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['9'],
        page_name: 'Гуманитарность, завершение',
        page_image: '',
        page_content: `- *Масло нероли* – снимает напряжение, помогает справиться с горем и утратой.
        - *Масло жасмина* – улучшает настроение, способствует эмоциональной открытости и сочувствию.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['1'],
        page_name: 'Лидерство, инициатива',
        page_image: '',
        page_content: `- *Масло розмарина* – стимулирует ум и концентрацию, добавляет энергии.
        - *Масло эвкалипта* – освежает, придаёт силы и помогает сосредоточиться.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['2'],
        page_name: 'Гармония, партнёрство',
        page_image: '',
        page_content: `- *Масло ромашки* – успокаивает, уменьшает стресс и способствует миру.
        - *Масло иланг-иланга* – уравновешивает эмоции, способствует релаксации.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['3'],
        page_name: 'Коммуникация, творчество',
        page_image: '',
        page_content: `- *Масло лимона* – стимулирует ум и поднимает настроение.
        - *Масло грейпфрута* – активизирует и освежает, поднимает дух.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['4'],
        page_name: 'Стабильность, порядок',
        page_image: '',
        page_content: `- *Масло кедра* – создаёт ощущение устойчивости и комфорта.
        - *Масло ветивера* – помогает укрепить нервную систему, добавляет уверенности.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['5'],
        page_name: 'Приключение, изменения',
        page_image: '',
        page_content: `- *Масло перечной мяты* – освежает, стимулирует новые идеи, придаёт энергию.
        - *Масло имбиря* – добавляет тепла и остроты, стимулирует движение вперёд.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['6'],
        page_name: 'Забота, ответственность',
        page_image: '',
        page_content: `- *Масло лаванды* – уменьшает анксиозность, способствует спокойствию и заботе.
        - *Масло розы* – улучшает настроение, помогает в эмоциональном балансе.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['7'],
        page_name: 'Духовность, мудрость',
        page_image: '',
        page_content: `- *Масло франкинсенса* – способствует медитации, углублению мыслей.
        - *Масло мирры* – поддерживает духовные практики, углубляет медитативные состояния.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['8'],
        page_name: 'Сила, успех',
        page_image: '',
        page_content: `- *Масло сандала* – помогает углубиться в себя, поддерживает при духовных поисках и медитации.
        - *Масло пачули* – укрепляет энергетический фон, способствует привлечению успеха.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        page_keys: ['9'],
        page_name: 'Гуманитарность, завершение',
        page_image: '',
        page_content: `- *Масло нероли* – снимает напряжение, помогает справиться с горем и утратой.
        - *Масло жасмина* – улучшает настроение, способствует эмоциональной открытости и сочувствию.`,
        language_code: 'en',
      },
    ])

    await queryRunner.manager.insert(Page, [
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['1'],
        page_name: 'I - Маг',
        page_image: '',
        page_content: `Мята — активизация ума и коммуникативных способностей.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['2'],
        page_name: 'II - Верховная Жрица',
        page_image: '',
        page_content: `Лунная трава — усиление интуиции и мистической мудрости.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['3'],
        page_name: 'III - Императрица',
        page_image: '',
        page_content: `Роза — плодородие, красота и забота.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['4'],
        page_name: 'IV - Император',
        page_image: '',
        page_content: `Кедр — стабильность, сила и защита.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['5'],
        page_name: 'V - Иерофант',
        page_image: '',
        page_content: `Франкинсенс — духовное просвещение и связь с традициями.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['6'],
        page_name: 'VI - Влюбленные',
        page_image: '',
        page_content: `Иланг-иланг — гармония отношений и страстная любовь.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['7'],
        page_name: 'VII - Колесница',
        page_image: '',
        page_content: `Черный перец — детерминация, смелость и преодоление препятствий.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['8'],
        page_name: 'VIII - Справедливость',
        page_image: '',
        page_content: `Ладан — ясность, честность и справедливость.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['9'],
        page_name: 'IX - Отшельник',
        page_image: '',
        page_content: `Сандал — медитация, внутренний поиск и просветление.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['10'],
        page_name: 'X - Колесо Фортуны',
        page_image: '',
        page_content: `Эвкалипт — изменения, гибкость и адаптация.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['11'],
        page_name: 'XI - Сила',
        page_image: '',
        page_content: `Корица — контроль над инстинктами, сила воли.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['12'],
        page_name: 'XII - Повешенный',
        page_image: '',
        page_content: `Пачули — видение мира с другой точки зрения, жертвенность.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['13'],
        page_name: 'XIII - Смерть',
        page_image: '',
        page_content: `Мирра — трансформация, окончание и новое начало.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['14'],
        page_name: 'XIV - Умеренность',
        page_image: '',
        page_content: `Лаванда — баланс, умиротворение и исцеление.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['15'],
        page_name: 'XV - Дьявол',
        page_image: '',
        page_content: `Ветивер — освобождение от зависимостей, глубокие страсти.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['16'],
        page_name: 'XVI - Башня',
        page_image: '',
        page_content: `Лимон — очищение, разрушение старого и внезапные прозрения.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['17'],
        page_name: 'XVII - Звезда',
        page_image: '',
        page_content: `Нероли — надежда, вдохновение и уверенность в будущем.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['18'],
        page_name: 'XVIII - Луна',
        page_image: '',
        page_content: `Жасмин — интуиция, сновидения и подсознательное.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['19'],
        page_name: 'XIX - Солнце',
        page_image: '',
        page_content: `Грейпфрут — радость, ясность и успех.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['20'],
        page_name: 'XX - Суд',
        page_image: '',
        page_content: `Ромашка — возрождение, чистый счет и духовное пробуждение.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['21'],
        page_name: 'XXI - Мир',
        page_image: '',
        page_content: `Нагиеток — завершение, целостность и мир.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['22', '0'],
        page_name: '0 ИЛИ 22 - Глупец',
        page_image: '',
        page_content: `Бергамот — символ новых начинаний и свободы.`,
        language_code: 'ru',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['1'],
        page_name: 'I - Маг',
        page_image: '',
        page_content: `Мята — активизация ума и коммуникативных способностей.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['2'],
        page_name: 'II - Верховная Жрица',
        page_image: '',
        page_content: `Лунная трава — усиление интуиции и мистической мудрости.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['3'],
        page_name: 'III - Императрица',
        page_image: '',
        page_content: `Роза — плодородие, красота и забота.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['4'],
        page_name: 'IV - Император',
        page_image: '',
        page_content: `Кедр — стабильность, сила и защита.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['5'],
        page_name: 'V - Иерофант',
        page_image: '',
        page_content: `Франкинсенс — духовное просвещение и связь с традициями.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['6'],
        page_name: 'VI - Влюбленные',
        page_image: '',
        page_content: `Иланг-иланг — гармония отношений и страстная любовь.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['7'],
        page_name: 'VII - Колесница',
        page_image: '',
        page_content: `Черный перец — детерминация, смелость и преодоление препятствий.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['8'],
        page_name: 'VIII - Справедливость',
        page_image: '',
        page_content: `Ладан — ясность, честность и справедливость.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['9'],
        page_name: 'IX - Отшельник',
        page_image: '',
        page_content: `Сандал — медитация, внутренний поиск и просветление.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['10'],
        page_name: 'X - Колесо Фортуны',
        page_image: '',
        page_content: `Эвкалипт — изменения, гибкость и адаптация.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['11'],
        page_name: 'XI - Сила',
        page_image: '',
        page_content: `Корица — контроль над инстинктами, сила воли.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['12'],
        page_name: 'XII - Повешенный',
        page_image: '',
        page_content: `Пачули — видение мира с другой точки зрения, жертвенность.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['13'],
        page_name: 'XIII - Смерть',
        page_image: '',
        page_content: `Мирра — трансформация, окончание и новое начало.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['14'],
        page_name: 'XIV - Умеренность',
        page_image: '',
        page_content: `Лаванда — баланс, умиротворение и исцеление.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['15'],
        page_name: 'XV - Дьявол',
        page_image: '',
        page_content: `Ветивер — освобождение от зависимостей, глубокие страсти.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['16'],
        page_name: 'XVI - Башня',
        page_image: '',
        page_content: `Лимон — очищение, разрушение старого и внезапные прозрения.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['17'],
        page_name: 'XVII - Звезда',
        page_image: '',
        page_content: `Нероли — надежда, вдохновение и уверенность в будущем.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['18'],
        page_name: 'XVIII - Луна',
        page_image: '',
        page_content: `Жасмин — интуиция, сновидения и подсознательное.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['19'],
        page_name: 'XIX - Солнце',
        page_image: '',
        page_content: `Грейпфрут — радость, ясность и успех.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['20'],
        page_name: 'XX - Суд',
        page_image: '',
        page_content: `Ромашка — возрождение, чистый счет и духовное пробуждение.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['21'],
        page_name: 'XXI - Мир',
        page_image: '',
        page_content: `Нагиеток — завершение, целостность и мир.`,
        language_code: 'en',
      },
      {
        page_type_id: PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
        page_keys: ['22', '0'],
        page_name: '0 ИЛИ 22 - Глупец',
        page_image: '',
        page_content: `Бергамот — символ новых начинаний и свободы.`,
        language_code: 'en',
      },
    ])
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.manager.delete(Page, {
      page_type_id: [
        PageTypesEnum.SOUL_NUMBER_ESSENTIAL_OIL,
        PageTypesEnum.DAY_ARCANE_ESSENTIAL_OIL,
      ],
    })
  }
}
