import { Page } from 'src/modules/page/entities/page.entity'
import { MigrationInterface, QueryRunner } from 'typeorm'

export class SeedPages1715779302029 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const placeholder =
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

    await queryRunner.manager.insert(Page, [
      {
        page_name: JSON.stringify({ ru: 'Программа судьбы', en: 'Программа судьбы' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/destiny.jpg',
        page_icon: '',
        color: '#0085FF',
        key: 'destiny-program',
        category_id: 1,
      },
      {
        page_name: JSON.stringify({
          ru: 'Сильные качества и таланты',
          en: 'Сильные качества и таланты',
        }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/strong-qualities.jpg',
        page_icon: '',
        color: '#4B3DAA',
        key: 'strong-qualities',
        category_id: 1,
      },
      {
        page_name: JSON.stringify({ ru: 'Карты судьбы', en: 'Карты судьбы' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/fate-cards.jpg',
        page_icon: '',
        color: '#796095',
        key: 'fate-card',
        category_id: 1,
      },
      {
        page_name: JSON.stringify({ ru: 'Слабые качества', en: 'Слабые качества' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/weak-qualities.jpg',
        page_icon: '',
        color: '#667176',
        key: 'weak-qualities',
        category_id: 1,
      },
      {
        page_name: JSON.stringify({ ru: 'Планеты', en: 'Планеты' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/planets.jpg',
        page_icon: '',
        color: '#4F3F39',
        key: 'planets',
        category_id: 1,
      },
      {
        page_name: JSON.stringify({ ru: 'Карма и прошлая жизнь', en: 'Карма и прошлая жизнь' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/karma.jpg',
        page_icon: '',
        color: '#004F6C',
        key: 'karma',
        category_id: 2,
      },
      {
        page_name: JSON.stringify({ ru: 'Нумерология здоровья', en: 'Нумерология здоровья' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/health.jpg',
        page_icon: '',
        color: '#2BB986',
        key: 'health',
        category_id: 3,
      },
      {
        page_name: JSON.stringify({
          ru: 'Группа крови и нумерология',
          en: 'Группа крови и нумерология',
        }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/blood-type.jpg',
        page_icon: '',
        color: '#D32F31',
        key: 'blood-type',
        category_id: 3,
      },
      {
        page_name: JSON.stringify({ ru: 'Ароматерапия', en: 'Ароматерапия' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/aromatherapy.jpg',
        page_icon: '',
        color: '#F05191',
        key: 'aromatherapy',
        category_id: 3,
      },
      {
        page_name: JSON.stringify({ ru: 'Графики', en: 'Графики' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/graphs.jpg',
        page_icon: '',
        color: '#5669CD',
        key: 'graph',
        category_id: 4,
      },
      {
        page_name: JSON.stringify({ ru: 'Расчет номера телефона', en: 'Расчет номера телефона' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/phone-number.jpg',
        page_icon: '',
        color: '#0085FF',
        key: 'phone-calculation',
        category_id: 5,
      },
      {
        page_name: JSON.stringify({ ru: 'Расчет номера дома', en: 'Расчет номера дома' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/house-number.jpg',
        page_icon: '',
        color: '#4B3DAA',
        key: 'house-calculation',
        category_id: 5,
      },
      {
        page_name: JSON.stringify({ ru: 'Прогноз', en: 'Прогноз' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/prediction.jpg',
        page_icon: '',
        color: '#F29F15',
        key: 'prediction',
        category_id: 5,
      },
      {
        page_name: JSON.stringify({ ru: 'Стиль по дате рождения', en: 'Стиль по дате рождения' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/style.jpg',
        page_icon: '',
        color: '#F05191',
        key: 'birthday-style',
        category_id: 6,
      },
      {
        page_name: JSON.stringify({ ru: 'Совместимость', en: 'Совместимость' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/relations.jpg',
        page_icon: '',
        color: '#00969F',
        key: 'compatibility',
        category_id: 7,
      },
      {
        page_name: JSON.stringify({ ru: 'Цветограмма человека', en: 'Цветограмма человека' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/colorgramm.jpg',
        page_icon: '',
        color: '#0091FB',
        key: 'color-graph',
        category_id: 8,
      },
      {
        page_name: JSON.stringify({
          ru: 'Рунические формулы на все случаи жизни',
          en: 'Рунические формулы на все случаи жизни',
        }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/runic-formulas.jpg',
        page_icon: '',
        color: '#0085FF',
        key: 'runic-formulas',
        category_id: 9,
      },
      {
        page_name: JSON.stringify({ ru: 'Подарки по числу судьбы', en: 'Подарки по числу судьбы' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/fate-gifts.jpg',
        page_icon: '',
        color: '#CE5A51',
        key: 'fate-number-gifts',
        category_id: 9,
      },
      {
        page_name: JSON.stringify({ ru: 'Тотемное животное', en: 'Тотемное животное' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/totemic-animal.jpg',
        page_icon: '',
        color: '#00A692',
        key: 'totemic-animals',
        category_id: 9,
      },
      {
        page_name: JSON.stringify({ ru: 'Числа удачи', en: 'Числа удачи' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/lucky-numbers.jpg',
        page_icon: '',
        color: '#F29F15',
        key: 'lucky-numbers',
        category_id: 9,
      },
      {
        page_name: JSON.stringify({ ru: 'Ангельская нумерология', en: 'Ангельская нумерология' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/angelic-numerology.jpg',
        page_icon: '',
        color: '#5EBBFF',
        key: 'angelic-numerology',
        category_id: 9,
      },
      {
        page_name: JSON.stringify({
          ru: 'Профессии и самореализация',
          en: 'Профессии и самореализация',
        }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/professions.jpg',
        page_icon: '',
        color: '#4B3016',
        key: 'professions',
        category_id: 9,
      },
      {
        page_name: JSON.stringify({ ru: 'Чтение мыслей по числам', en: 'Чтение мыслей по числам' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/guessing-numbers.jpg',
        page_icon: '',
        color: '#4B3DAA',
        key: 'guessing-number',
        category_id: 9,
      },
      {
        page_name: JSON.stringify({ ru: 'Кем были ваши предки', en: 'Кем были ваши предки' }),
        page_description: JSON.stringify({ ru: placeholder, en: placeholder }),
        page_image: '/files/uploads?path=uploads/images/pages/ancestors.jpg',
        page_icon: '',
        color: '#FF7C7C',
        key: 'ancestors',
        category_id: 9,
      },
    ])
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.clearTable('Pages')
  }
}
