import { Page } from 'src/modules/page/entities/page.entity'
import { MigrationInterface, QueryRunner } from 'typeorm'

export class SeedPagesEn1715846128747 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const placeholder =
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

    await queryRunner.manager.insert(Page, [
      {
        page_name: 'Программа судьбы',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/destiny.jpg',
        page_icon: '',
        color: '#0085FF',
        key: 'destiny-program',
        language_code: 'en',
        category_id: 1,
      },
      {
        page_name: 'Сильные качества и таланты',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/strong-qualities.jpg',
        page_icon: '',
        color: '#4B3DAA',
        key: 'strong-qualities',
        language_code: 'en',
        category_id: 1,
      },
      {
        page_name: 'Карты судьбы',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/fate-cards.jpg',
        page_icon: '',
        color: '#796095',
        key: 'fate-card',
        language_code: 'en',
        category_id: 1,
      },
      {
        page_name: 'Слабые качества',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/weak-qualities.jpg',
        page_icon: '',
        color: '#667176',
        key: 'weak-qualities',
        language_code: 'en',
        category_id: 1,
      },
      {
        page_name: 'Планеты',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/planets.jpg',
        page_icon: '',
        color: '#4F3F39',
        key: 'planets',
        language_code: 'en',
        category_id: 1,
      },
      {
        page_name: 'Карма и прошлая жизнь',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/karma.jpg',
        page_icon: '',
        color: '#004F6C',
        key: 'karma',
        language_code: 'en',
        category_id: 2,
      },
      {
        page_name: 'Нумерология здоровья',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/health.jpg',
        page_icon: '',
        color: '#2BB986',
        key: 'health',
        language_code: 'en',
        category_id: 3,
      },
      {
        page_name: 'Группа крови и нумерология',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/blood-type.jpg',
        page_icon: '',
        color: '#D32F31',
        key: 'blood-type',
        language_code: 'en',
        category_id: 3,
      },
      {
        page_name: 'Ароматерапия',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/aromatherapy.jpg',
        page_icon: '',
        color: '#F05191',
        key: 'aromatherapy',
        language_code: 'en',
        category_id: 3,
      },
      {
        page_name: 'Графики',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/graphs.jpg',
        page_icon: '',
        color: '#5669CD',
        key: 'graph',
        language_code: 'en',
        category_id: 4,
      },
      {
        page_name: 'Расчет номера телефона',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/phone-number.jpg',
        page_icon: '',
        color: '#0085FF',
        key: 'phone-calculation',
        language_code: 'en',
        category_id: 5,
      },
      {
        page_name: 'Расчет номера дома',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/house-number.jpg',
        page_icon: '',
        color: '#4B3DAA',
        key: 'house-calculation',
        language_code: 'en',
        category_id: 5,
      },
      {
        page_name: 'Прогноз',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/prediction.jpg',
        page_icon: '',
        color: '#F29F15',
        key: 'prediction',
        language_code: 'en',
        category_id: 5,
      },
      {
        page_name: 'Стиль по дате рождения',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/style.jpg',
        page_icon: '',
        color: '#F05191',
        key: 'birthday-style',
        language_code: 'en',
        category_id: 6,
      },
      {
        page_name: 'Совместимость',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/relations.jpg',
        page_icon: '',
        color: '#00969F',
        key: 'compatibility',
        language_code: 'en',
        category_id: 7,
      },
      {
        page_name: 'Цветограмма человека',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/colorgramm.jpg',
        page_icon: '',
        color: '#0091FB',
        key: 'color-graph',
        language_code: 'en',
        category_id: 8,
      },
      {
        page_name: 'Рунические формулы на все случаи жизни',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/runic-formulas.jpg',
        page_icon: '',
        color: '#0085FF',
        key: 'runic-formulas',
        language_code: 'en',
        category_id: 9,
      },
      {
        page_name: 'Подарки по числу судьбы',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/fate-gifts.jpg',
        page_icon: '',
        color: '#CE5A51',
        key: 'fate-number-gifts',
        language_code: 'en',
        category_id: 9,
      },
      {
        page_name: 'Тотемное животное',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/totemic-animal.jpg',
        page_icon: '',
        color: '#00A692',
        key: 'totemic-animals',
        language_code: 'en',
        category_id: 9,
      },
      {
        page_name: 'Числа удачи',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/lucky-numbers.jpg',
        page_icon: '',
        color: '#F29F15',
        key: 'lucky-numbers',
        language_code: 'en',
        category_id: 9,
      },
      {
        page_name: 'Ангельская нумерология',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/angelic-numerology.jpg',
        page_icon: '',
        color: '#5EBBFF',
        key: 'angelic-numerology',
        language_code: 'en',
        category_id: 9,
      },
      {
        page_name: 'Профессии и самореализация',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/professions.jpg',
        page_icon: '',
        color: '#4B3016',
        key: 'professions',
        language_code: 'en',
        category_id: 9,
      },
      {
        page_name: 'Чтение мыслей по числам',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/guessing-numbers.jpg',
        page_icon: '',
        color: '#4B3DAA',
        key: 'guessing-number',
        language_code: 'en',
        category_id: 9,
      },
      {
        page_name: 'Кем были ваши предки',
        page_description: placeholder,
        page_image: '/files/uploads?path=uploads/images/pages/ancestors.jpg',
        page_icon: '',
        color: '#FF7C7C',
        key: 'ancestors',
        language_code: 'en',
        category_id: 9,
      },
    ])
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.clearTable('Pages')
  }
}
