import { FormulaTypesEnum } from 'src/common/constants/constants'
import { FormulaResult } from 'src/modules/formula-result/entities/formula-result.entity'
import { MigrationInterface, QueryRunner } from 'typeorm'

export class SeedAngelicNumerology1717676459362 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.manager.insert(FormulaResult, [
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['02:22'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['03:03'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['03:30'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['03:33'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['04:04'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['04:40'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['04:44'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['05:50'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['05:55'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['06:06'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['07:07'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['07:17'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['08:08'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['08:18'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['09:09'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['09:19'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['10:01'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['10:10'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['11:00'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['11:01'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['11:10'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['11:11'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['11:21'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['11:22'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['11:33'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['11:44'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['11:55'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['12:12'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['12:21'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['12:22'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['13:03'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['13:13'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['13:31'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['13:33'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['14:14'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['14:44'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['14:41'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['15:15'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['15:51'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['15:55'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['16:16'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['17:07'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['17:17'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['18:08'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['18:18'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['19:09'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['19:19'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['20:02'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['20:20'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['20:22'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['21:11'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['21:12'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['21:21'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['21:22'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['22:00'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['22:02'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['22:11'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['22:12'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['22:20'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['22:21'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['22:22'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['22:33'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['22:44'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['22:55'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['23:23'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['23:32'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['23:33'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['23:45'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
      {
        formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
        result_keys: ['00:00'],
        result_name: JSON.stringify({ ru: '', en: '' }),
        result_content: JSON.stringify({ ru: '', en: '' }),
      },
    ])
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.manager.delete(FormulaResult, {
      formula_type_id: FormulaTypesEnum.ANGELIC_NUMEROLOGY,
    })
  }
}
